### ISSUE TITLE
[BUG] no queue pop

### ISSUE THREAD

**Issue by FrostyJef** [hawolt/custom-league-client#32] opened 2023-08-19 20:36 UTC
there is no queue pop when queueing, timer just stops

**Comment by FrostyJef** [comment] 2023-08-19 20:47
fixed, was lpq

**Comment by FrostyJef** [comment] 2023-08-19 20:48
not fixed :)

**Comment by hawolt** [comment] 2023-08-20 02:49
closing this as duplicate of https://github.com/hawolt/custom-league-client/issues/26

**Closed by hawolt** 2023-08-20 02:49 UTC
Labels: bug
