### ISSUE TITLE
Unknown Error during login

### ISSUE THREAD

**Issue by HeroRickyGAMES** [hawolt/custom-league-client#67] opened 2023-08-29 20:56 UTC
When I try to login using this custom client this appears: Unknown Error during login
Region: BR.
I already have everything installed, including intellij

**Comment by xthesebx** [comment] 2023-08-29 21:17
what release/branch are you using?

**Comment by zRevenger** [comment] 2023-08-29 21:25
This is happening on the main league client too and is most likely not related to this repository

**Comment by hawolt** [comment] 2023-09-01 09:57
could have been both 2FA or using an outdated client, both should work properly now on dev branch
will close this issue once I publish a new release

**Comment by HeroRickyGAMES** [comment] 2023-09-01 13:21
I tested it on my main and tested it on my secondary and it gave the same problem.
My main has 2FA, but the secondary does not.

**Comment by hawolt** [comment] 2023-09-02 17:39
should be resolved, fixed in latest release - his was caused by an invalid request

**Closed by hawolt** 2023-09-02 17:39 UTC
Labels: bug
